### ISSUE TITLE
页面宽度

### ISSUE THREAD

**Issue by happypeter** [happypeter/haoduoshipin#320]
有朋友来信给了这两行代码
```
body{min-width:990px;}
.container{overflow:hidden;}
```

我在 iphone 下看网站，确实跟信中切图类似，就是有白边。

**Comment by billie66** [comment]
放大页面直到出现横向滚动条，背景色消失，右边出现白边，之前就遇到过这个问题。

参考github的解决方案, 在使用背景色的区域限制一下最小宽度

```css
.header, .banner {
  min-width: 1100px;
}
```

**Comment by billie66** [comment]
我先按照 github 的方法修改了代码，在大屏幕上不会出现白边，但在手机上白色背景部分的内容不居中

**Comment by billie66** [comment]
```css
body{min-width:990px;}
.container{overflow:hidden;}
```

上面的代码部署之后，手机显示页面没有白边了，内容也居中

**Comment by billie66** [comment]
遇到一个问题，若这样设置

```css
.container{overflow: hidden;}
```

微信和支付宝的二维码都不能显示
